import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';

test('usa Google Sans locale con una scala tipografica leggibile', async () => {
  const styles = await fs.readFile(new URL('../core/web/styles.template.css', import.meta.url), 'utf8');
  assert.match(styles, /font-family: "Google Sans"/);
  assert.match(styles, /url\("\/fonts\/google-sans\/google-sans-latin\.woff2"\)/);
  assert.match(styles, /font-size: 18px/);
  assert.match(styles, /\[data-theme="dark"\]/);
  assert.match(styles, /@media \(max-width: 899px\)/);
  assert.match(styles, /@media \(max-width: 699px\)[^]*\.app-layout\s*{[^}]*min-height:\s*calc\(100vh - 7\.25rem\)/s);
  assert.match(styles, /@media \(min-width: 900px\)/);
  assert.match(styles, /body\.sidebar-collapsed \.app-layout/);
  assert.match(styles, /ionicons\/menu-outline\.svg/);
  assert.match(styles, /ionicons\/search-outline\.svg/);
  assert.match(styles, /ionicons\/close-outline\.svg/);
  assert.match(styles, /ionicons\/moon-outline\.svg/);
  assert.doesNotMatch(styles, /\[data-theme="dark"\]\s+\.icon--theme\s*{[^}]*sunny-outline\.svg/s);
  assert.match(styles, /--navigation-gutter:\s*1\.35rem/);
  assert.match(styles, /--sidebar-width:\s*clamp\(17rem, 25vw, 21rem\)/);
  assert.match(styles, /\.app-layout\s*{[^}]*grid-template-columns:\s*var\(--sidebar-width\) minmax\(0, 1fr\)[^}]*transition:\s*grid-template-columns 180ms ease/s);
  assert.match(styles, /\.app-sidebar > \.navigation\s*{[^}]*width:\s*calc\(var\(--sidebar-width\) - \(2 \* var\(--navigation-gutter\)\)\)/s);
  assert.match(styles, /\.navigation > ol\s*{[^}]*padding-left:\s*1\.85rem[^}]*list-style:\s*decimal/s);
  assert.match(styles, /\.navigation ul\s*{[^}]*padding-left:\s*1\.15rem[^}]*list-style:\s*disc/s);
  assert.doesNotMatch(styles, /\.navigation > ol\s*{[^}]*list-style:\s*none/s);
  assert.match(styles, /\.app-header\s*{[^}]*gap:\s*0\.325rem/s);
  assert.match(styles, /\.app-header__menu\s*{[^}]*margin-inline-start:\s*calc\(var\(--navigation-gutter\) - var\(--header-inline-padding\) - var\(--menu-toggle-glyph-offset\)\)/s);
  assert.doesNotMatch(styles, /\.app-header__menu\s*{[^}]*transform:/s);
  assert.match(styles, /\.app-header__brand\s*{[^}]*display:\s*inline-flex[^}]*gap:\s*0\.45rem/s);
  assert.match(styles, /\.app-header__logo\s*{[^}]*width:\s*1\.75rem[^}]*height:\s*1\.75rem[^}]*object-fit:\s*contain/s);
  assert.match(styles, /\.app-header__title\s*{[^}]*text-overflow:\s*ellipsis[^}]*white-space:\s*nowrap/s);
  assert.match(styles, /\.search-launcher\s*{[^}]*border-radius:\s*999px/s);
  assert.match(styles, /\.search-dialog__field input\s*{[^}]*border-radius:\s*999px/s);
  assert.match(styles, /search-cancel-button[^}]*-webkit-appearance:\s*none/s);
  assert.match(styles, /\.search-clear\s*{[^}]*position:\s*absolute[^}]*border-radius:\s*50%/s);
  assert.match(styles, /\.search-clear\[hidden\]\s*{[^}]*display:\s*none/s);
  assert.match(styles, /\.search-clear \.icon\s*{[^}]*width:\s*1\.9rem[^}]*height:\s*1\.9rem/s);
  assert.doesNotMatch(styles, /\.search-result__route/);
  assert.match(styles, /\.search-result__snippet\s*{[^}]*font-size:\s*0\.9rem/s);
  assert.match(styles, /\.search-overlay\s*{[^}]*z-index:\s*100/s);
  assert.match(styles, /@media \(max-width: 699px\)[^]*\.app-header__search\s*{[^}]*flex-basis:\s*100%/s);
  assert.match(styles, /@media \(max-width: 699px\)[^]*scroll-margin-top:\s*9rem/s);
  assert.match(styles, /@media \(max-width: 599px\)[^]*\.search-dialog\s*{[^}]*height:\s*100dvh/s);
  assert.match(styles, /\.app-sidebar\s*{[^}]*padding:\s*1\.75rem var\(--navigation-gutter\) 3rem/s);
  assert.match(styles, /\.app-sidebar\s*{[^}]*opacity:\s*1[^}]*transition:[^}]*opacity 180ms ease/s);
  assert.match(styles, /body\.sidebar-collapsed \.app-sidebar\s*{[^}]*opacity:\s*0[^}]*visibility:\s*hidden[^}]*pointer-events:\s*none/s);
  assert.match(styles, /@media \(max-width: 899px\)[^]*\.app-sidebar\s*{[^}]*opacity:\s*0[^}]*transform:\s*translateX\(-105%\)[^}]*pointer-events:\s*none/s);
  assert.match(styles, /@media \(max-width: 899px\)[^]*\.app-sidebar\.is-open\s*{[^}]*opacity:\s*1[^}]*transform:\s*translateX\(0\)[^}]*pointer-events:\s*auto/s);
  assert.match(styles, /@media \(prefers-reduced-motion: reduce\)[^]*transition-duration:\s*0\.01ms !important/s);
  assert.match(styles, /--reading-progress/);
  assert.match(styles, /@media print/);
  assert.match(styles, /body\.export-printing \.app-header, body\.export-printing \.app-layout\s*{[^}]*display:\s*none/s);
  assert.match(styles, /body\.export-printing \.print-export\s*{[^}]*display:\s*block/s);
  assert.match(styles, /body\.export-printing \.print-export__navigation\s*{[^}]*break-after:\s*page/s);
  assert.match(styles, /body\.export-printing \.print-export__document\s*{[^}]*break-before:\s*page/s);
  assert.match(styles, /@media print\s*{[^]*body\.export-printing\s*{[^}]*color-scheme:\s*light/s);
  assert.match(styles, /@media print\s*{[^]*body\.export-printing\s*{[^}]*--background:\s*#ffffff[^}]*--text:\s*#202124[^}]*--code-background:\s*#202124[^}]*--code-text:\s*#f8fafc/s);
  assert.match(styles, /\[data-theme="dark"\][^]*@media print[^]*body\.export-printing\s*{[^}]*--surface:\s*#ffffff/s);
  assert.doesNotMatch(styles, /(?:^|\})\s*\.app-header, \.app-layout\s*{[^}]*display:\s*none/s);
  assert.doesNotMatch(styles, /fonts\.googleapis\.com|fonts\.gstatic\.com/);
});
